name: Rust

on:
  push:
    tags:
      '*'

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # 最小化构建配置，目标小于1MB
        include:
          - TARGET: x86_64-unknown-linux-musl
            OS: ubuntu-latest
            FEATURES: aes_gcm,server_encrypt
          - TARGET: x86_64-pc-windows-msvc
            OS: windows-latest
            FEATURES: aes_gcm,server_encrypt
          - TARGET: x86_64-apple-darwin
            OS: macos-latest
            FEATURES: aes_gcm,server_encrypt
          - TARGET: aarch64-apple-darwin
            OS: macos-latest
            FEATURES: aes_gcm,server_encrypt
    runs-on: ${{ matrix.OS }}
    env:
      NAME: vnt-cli
      TARGET: ${{ matrix.TARGET }}
      OS: ${{ matrix.OS }}
      FEATURES: ${{ matrix.FEATURES }}
    steps:
      - uses: actions/checkout@v4
      - name: Init submodules
        uses: snickerbockers/submodules-init@v4
      - name: Cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ./target
          key: build-cargo-registry-${{matrix.TARGET}}
      - name: Use strawberry perl
        if: startsWith(matrix.os, 'windows')
        run: echo OPENSSL_SRC_PERL=C:/Strawberry/perl/bin/perl >> $GITHUB_ENV
      - name: Install and configure dependencies
        run: |
          rustup set auto-self-update disable

          if [[ $OS =~ ^ubuntu.*$ ]]; then
            sudo apt-get update && sudo apt-get install clang llvm libc6-dev-i386 crossbuild-essential-arm64 crossbuild-essential-armhf musl-tools libboost-all-dev libc6-dev -y
          else
            rustup install 1.77
            rustup default 1.77
          fi
          rustup -V

          # 最小化体积的优化配置
          cat >>~/.cargo/config <<EOF
          [target.x86_64-unknown-linux-musl]
          rustflags = ["-C", "target-feature=+crt-static","-C", "strip=symbols"]
          [target.x86_64-pc-windows-msvc]
          rustflags = ["-C", "target-feature=+crt-static","-C", "strip=symbols"]
          [target.x86_64-apple-darwin]
          rustflags = ["-C", "target-feature=+crt-static","-C", "strip=symbols"]
          [target.aarch64-apple-darwin]
          rustflags = ["-C", "target-feature=+crt-static","-C", "strip=symbols"]
          EOF
      - name: Install rust target
        run: rustup target add $TARGET
      - name: Run build vn-link-cli
        run: cargo build --package vn-link-cli --release --verbose --target $TARGET --features $FEATURES
      - name: Run build vnt-cli
        run: cargo build --package vnt-cli --release --verbose --target $TARGET --features $FEATURES
      - name: Compress
        run: |
          mkdir -p ./artifacts
          if [[ $OS =~ ^windows.*$ ]]; then
              EXEC_VNT_CLI=vnt-cli.exe
              EXEC_VN_LINK_CLI=vn-link-cli.exe
          else
              EXEC_VNT_CLI=vnt-cli
              EXEC_VN_LINK_CLI=vn-link-cli
          fi
          if [[ $GITHUB_REF_TYPE =~ ^tag$ ]]; then
            TAG=$GITHUB_REF_NAME
          else
            TAG=$GITHUB_SHA
          fi
          mv ./target/$TARGET/release/$EXEC_VNT_CLI ./artifacts/$EXEC_VNT_CLI
          mv ./target/$TARGET/release/$EXEC_VN_LINK_CLI ./artifacts/$EXEC_VN_LINK_CLI
          mv ./README ./artifacts/README.txt
          cd ./artifacts
          tar -czf vnt-$TARGET-$TAG.tar.gz *
          mkdir upload_file
          mv vnt-$TARGET-$TAG.tar.gz ./upload_file/
      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: vnt-cli-${{ matrix.TARGET }}
          path: |
            ./artifacts/upload_file
  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.YOURTOKEN }}
          file: ./artifacts/**/*.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true